Update gLiveView

diff --git a/scripts/env b/scripts/env
--- a/scripts/env
+++ b/scripts/env
@@ -80,7 +80,7 @@ fi
 
 [[ -z ${CURL_TIMEOUT} ]] && CURL_TIMEOUT=10
 
-# 
+#
 telegramSend() {
   if [[ -z "${TG_BOT_TOKEN}" ]] || [[ -z "${TG_CHAT_ID}" ]]; then
     echo "Warn: to use the telegramSend function you must first set the bot and chat id in the env file"
@@ -103,11 +103,6 @@ if [[ -z "${CCLI}" ]]; then
 else
   CCLI_PARENT="$(dirname ${CCLI})"
   export PATH="${CCLI_PARENT}":$PATH
-fi
-node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "1.25.1" "${node_version}"; then
-  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.25.1 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
-  return 1
 fi
 
 if [[ -z "${CNCLI}" ]]; then
@@ -272,35 +267,14 @@ if [[ -n "${CNODE_PID}" ]]; then
   fi
 fi
 
-PROTOCOL=$(jq -r .Protocol "${CONFIG}")
-NETWORKID=$(jq -r .networkId ${GENESIS_JSON})
-MAGIC=$(jq -r .protocolMagicId < ${GENESIS_JSON})
-NWMAGIC=$(jq -r .networkMagic < ${GENESIS_JSON})
-[[ ${NETWORKID} = "Mainnet" ]] && HASH_IDENTIFIER="--mainnet" || HASH_IDENTIFIER="--testnet-magic ${NWMAGIC}"
-case ${NWMAGIC} in
-  764824073) NETWORK_NAME="Mainnet"; SHELLEY_TRANS_EPOCH=208; NETWORK_IDENTIFIER="--mainnet" ;;
-  1097911063) NETWORK_NAME="Testnet"; SHELLEY_TRANS_EPOCH=74; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
-  633343913) NETWORK_NAME="Staging"; SHELLEY_TRANS_EPOCH=208; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
-  141) NETWORK_NAME="Guild"; SHELLEY_TRANS_EPOCH=1; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
-  *) NETWORK_NAME="Custom"; SHELLEY_TRANS_EPOCH=-1; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
-esac
-
-SHELLEY_GENESIS_START_SEC=$(date --date="$(jq -r .systemStart "${GENESIS_JSON}")" +%s)
-EPOCH_LENGTH=$(jq -r .epochLength "${GENESIS_JSON}")
-SLOT_LENGTH=$(jq -r .slotLength "${GENESIS_JSON}")
-ACTIVE_SLOTS_COEFF=$(jq -r .activeSlotsCoeff "${GENESIS_JSON}")
-SLOTS_PER_KES_PERIOD=$(jq -r .slotsPerKESPeriod "${GENESIS_JSON}")
-MAX_KES_EVOLUTIONS=$(jq -r .maxKESEvolutions "${GENESIS_JSON}")
-BYRON_GENESIS_START_SEC=$(jq -r .startTime "${BYRON_GENESIS_JSON}")
-BYRON_K=$(jq -r .protocolConsts.k "${BYRON_GENESIS_JSON}")
-BYRON_SLOT_LENGTH=$(( $(jq -r .blockVersionData.slotDuration "${BYRON_GENESIS_JSON}") ))
-BYRON_EPOCH_LENGTH=$(( 10 * BYRON_K ))
-
 [[ -z ${TOPOLOGY} ]] && TOPOLOGY="${CNODE_HOME}/files/topology.json"
 [[ -n ${CNODE_TOPOLOGY} ]] && TOPOLOGY="${CNODE_TOPOLOGY}" # compatibility with older topologyUpdater
 [[ -z ${LOG_DIR} ]] && LOG_DIR="${CNODE_HOME}/logs"
 [[ -n ${CNODE_LOG_DIR} ]] && LOG_DIR="${CNODE_LOG_DIR}" # compatibility with older topologyUpdater
 [[ -z ${DB_DIR} ]] && DB_DIR="${CNODE_HOME}/db"
+[[ -z ${TMP_DIR} ]] && TMP_DIR="/tmp/$(basename "${CNODE_HOME}")"
+if ! mkdir -p "${TMP_DIR}" 2>/dev/null; then echo "ERROR: Failed to create directory for temporary files, please set TMP_DIR to a valid folder in 'env', current folder: ${TMP_DIR}" && exit 1; fi
+[[ -z ${TIMEOUT_LEDGER_STATE} ]] && TIMEOUT_LEDGER_STATE=300
 [[ -z ${WALLET_FOLDER} ]] && WALLET_FOLDER="${CNODE_HOME}/priv/wallet"
 [[ -z ${POOL_FOLDER} ]] && POOL_FOLDER="${CNODE_HOME}/priv/pool"
 [[ -z ${POOL_NAME} ]] && POOL_NAME="CHANGE_ME"
@@ -330,6 +304,41 @@ BYRON_EPOCH_LENGTH=$(( 10 * BYRON_K ))
 [[ -z ${POOL_REGCERT_FILENAME} ]] && POOL_REGCERT_FILENAME="pool.cert"
 [[ -z ${POOL_CURRENT_KES_START} ]] && POOL_CURRENT_KES_START="kes.start"
 [[ -z ${POOL_DEREGCERT_FILENAME} ]] && POOL_DEREGCERT_FILENAME="pool.dereg"
+[[ -z ${ASSET_FOLDER} ]] && ASSET_FOLDER="${CNODE_HOME}/priv/asset"
+[[ -z ${ASSET_POLICY_VK_FILENAME} ]] && ASSET_POLICY_VK_FILENAME="policy.vkey"
+[[ -z ${ASSET_POLICY_SK_FILENAME} ]] && ASSET_POLICY_SK_FILENAME="policy.skey"
+[[ -z ${ASSET_POLICY_SCRIPT_FILENAME} ]] && ASSET_POLICY_SCRIPT_FILENAME="policy.script"
+[[ -z ${ASSET_POLICY_ID_FILENAME} ]] && ASSET_POLICY_ID_FILENAME="policy.id"
+
+node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
+if ! versionCheck "1.25.1" "${node_version}"; then
+  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.25.1 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
+  return 1
+fi
+
+PROTOCOL=$(jq -r .Protocol "${CONFIG}")
+NETWORKID=$(jq -r .networkId ${GENESIS_JSON})
+MAGIC=$(jq -r .protocolMagicId < ${GENESIS_JSON})
+NWMAGIC=$(jq -r .networkMagic < ${GENESIS_JSON})
+[[ ${NETWORKID} = "Mainnet" ]] && HASH_IDENTIFIER="--mainnet" || HASH_IDENTIFIER="--testnet-magic ${NWMAGIC}"
+case ${NWMAGIC} in
+  764824073) NETWORK_NAME="Mainnet"; [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=208; NETWORK_IDENTIFIER="--mainnet" ;;
+  1097911063) NETWORK_NAME="Testnet"; [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=74; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
+  633343913) NETWORK_NAME="Staging"; [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=208; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
+  141) NETWORK_NAME="Guild"; [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=1; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
+  *) NETWORK_NAME="Custom"; [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=-1; NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}" ;;
+esac
+
+SHELLEY_GENESIS_START_SEC=$(date --date="$(jq -r .systemStart "${GENESIS_JSON}")" +%s)
+EPOCH_LENGTH=$(jq -r .epochLength "${GENESIS_JSON}")
+SLOT_LENGTH=$(jq -r .slotLength "${GENESIS_JSON}")
+ACTIVE_SLOTS_COEFF=$(jq -r .activeSlotsCoeff "${GENESIS_JSON}")
+SLOTS_PER_KES_PERIOD=$(jq -r .slotsPerKESPeriod "${GENESIS_JSON}")
+MAX_KES_EVOLUTIONS=$(jq -r .maxKESEvolutions "${GENESIS_JSON}")
+BYRON_GENESIS_START_SEC=$(jq -r .startTime "${BYRON_GENESIS_JSON}")
+BYRON_K=$(jq -r .protocolConsts.k "${BYRON_GENESIS_JSON}")
+BYRON_SLOT_LENGTH=$(( $(jq -r .blockVersionData.slotDuration "${BYRON_GENESIS_JSON}") ))
+BYRON_EPOCH_LENGTH=$(( 10 * BYRON_K ))
 
 FG_BLACK='\e[30m'
 FG_RED='\e[31m'
@@ -370,32 +379,32 @@ getNodeMetrics() {
   if [[ ${USE_EKG} = 'Y' ]]; then
     node_metrics=$(curl -s -m ${EKG_TIMEOUT} -H 'Accept: application/json' "http://${EKG_HOST}:${EKG_PORT}/" 2>/dev/null)
     node_metrics_tsv=$(jq -r '[
-.cardano.node.metrics.blockNum.int.val //0,
-.cardano.node.metrics.epoch.int.val //0,
-.cardano.node.metrics.slotInEpoch.int.val //0,
-.cardano.node.metrics.slotNum.int.val //0,
-.cardano.node.metrics.density.real.val //"-",
-.cardano.node.metrics.txsProcessedNum.int.val //0,
-.cardano.node.metrics.txsInMempool.int.val //0,
-.cardano.node.metrics.mempoolBytes.int.val //0,
-.cardano.node.metrics.currentKESPeriod.int.val //0,
-.cardano.node.metrics.remainingKESPeriods.int.val //0,
-.cardano.node.metrics.Forge["node-is-leader"].int.val //0,
-.cardano.node.metrics.Forge.adopted.int.val //0,
-.cardano.node.metrics.Forge["didnt-adopt"].int.val //0,
-.cardano.node.metrics.Forge["forge-about-to-lead"].int.val //0,
-.rts.gc.wall_ms.val //0
-] | @tsv' <<< "${node_metrics}")
+    .cardano.node.metrics.blockNum.int.val //0,
+    .cardano.node.metrics.epoch.int.val //0,
+    .cardano.node.metrics.slotInEpoch.int.val //0,
+    .cardano.node.metrics.slotNum.int.val //0,
+    .cardano.node.metrics.density.real.val //"-",
+    .cardano.node.metrics.txsProcessedNum.int.val //0,
+    .cardano.node.metrics.txsInMempool.int.val //0,
+    .cardano.node.metrics.mempoolBytes.int.val //0,
+    .cardano.node.metrics.currentKESPeriod.int.val //0,
+    .cardano.node.metrics.remainingKESPeriods.int.val //0,
+    .cardano.node.metrics.Forge["node-is-leader"].int.val //0,
+    .cardano.node.metrics.Forge.adopted.int.val //0,
+    .cardano.node.metrics.Forge["didnt-adopt"].int.val //0,
+    .cardano.node.metrics.Forge["forge-about-to-lead"].int.val //0,
+    .cardano.node.metrics.nodeStartTime.int.val //0
+    ] | @tsv' <<< "${node_metrics}")
     read -ra node_metrics_arr <<< ${node_metrics_tsv}
     blocknum=${node_metrics_arr[0]}; epochnum=${node_metrics_arr[1]}; slot_in_epoch=${node_metrics_arr[2]}; slotnum=${node_metrics_arr[3]}
     [[ ${node_metrics_arr[4]} != '-' ]] && density=$(bc <<< "scale=3;$(printf '%3.5f' "${node_metrics_arr[4]}")*100/1") || density=0.0
     tx_processed=${node_metrics_arr[5]}; mempool_tx=${node_metrics_arr[6]}; mempool_bytes=${node_metrics_arr[7]}
     kesperiod=${node_metrics_arr[8]}; remaining_kes_periods=${node_metrics_arr[9]}
     isleader=${node_metrics_arr[10]}; adopted=${node_metrics_arr[11]}; didntadopt=${node_metrics_arr[12]}; about_to_lead=${node_metrics_arr[13]}
-    uptimens=${node_metrics_arr[14]}
+    uptimes=$(( $(date +%s) - node_metrics_arr[14] ))
   else
     node_metrics=$(curl -s -m ${EKG_TIMEOUT} "http://${PROM_HOST}:${PROM_PORT}/metrics" 2>/dev/null)
-    [[ ${node_metrics} =~ rts_gc_wall_ms[[:space:]]([^[:space:]]*) ]] && uptimens=${BASH_REMATCH[1]} || uptimens=0
+    [[ ${node_metrics} =~ cardano_node_metrics_nodeStartTime_int[[:space:]]([^[:space:]]*) ]] && uptimes=$(( $(date +%s) - BASH_REMATCH[1] )) || uptimes=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockNum_int[[:space:]]([^[:space:]]*) ]] && blocknum=${BASH_REMATCH[1]} || blocknum=0
     [[ ${node_metrics} =~ cardano_node_metrics_epoch_int[[:space:]]([^[:space:]]*) ]] && epochnum=${BASH_REMATCH[1]} || epochnum=0
     [[ ${node_metrics} =~ cardano_node_metrics_slotInEpoch_int[[:space:]]([^[:space:]]*) ]] && slot_in_epoch=${BASH_REMATCH[1]} || slot_in_epoch=0
@@ -454,10 +463,12 @@ getSlotInEpochFromSlot() {
 }
 
 # Description : Offline calculation of date based on provided slot number
+#             : $1 = slot, $2 = (optional) printf date format
 getDateFromSlot() {
   byron_slots=$(( SHELLEY_TRANS_EPOCH * BYRON_EPOCH_LENGTH ))
-  printf -v date_from_slot '%(%FT%T%z)T' $(( ((byron_slots * BYRON_SLOT_LENGTH) / 1000) + (($1-byron_slots) * SLOT_LENGTH) + SHELLEY_GENESIS_START_SEC ))
-  echo "${date_from_slot%??}:${date_from_slot: -2}"
+  [[ -n $2 ]] && date_fmt="$2" || date_fmt='%(%FT%T%z)T'
+  printf -v date_from_slot "${date_fmt}" $(( ((byron_slots * BYRON_SLOT_LENGTH) / 1000) + (($1-byron_slots) * SLOT_LENGTH) + SHELLEY_GENESIS_START_SEC ))
+  [[ -n $2 ]] && echo "${date_from_slot}" || echo "${date_from_slot%??}:${date_from_slot: -2}"
 }
 
 # Description : Offline calculation of time in seconds until next epoch
@@ -510,7 +521,7 @@ getEraIdentifier() {
   elif ${CCLI} query protocol-parameters --shelley-era ${NETWORK_IDENTIFIER} &>/dev/null; then ERA_IDENTIFIER="--shelley-era"
   elif ${CCLI} query protocol-parameters --allegra-era ${NETWORK_IDENTIFIER} &>/dev/null; then ERA_IDENTIFIER="--allegra-era"
   elif ${CCLI} query protocol-parameters --mary-era ${NETWORK_IDENTIFIER} &>/dev/null; then ERA_IDENTIFIER="--mary-era"
-  else 
+  else
     ERA_IDENTIFIER=""
     [[ ${OFFLINE_MODE} = "N" ]] && return 1
   fi
