Update gLiveView

diff --git a/scripts/env b/scripts/env
--- a/scripts/env
+++ b/scripts/env
@@ -64,6 +64,12 @@ SOCKET="/opt/cardano-node/socket"                       # Override automatic det
 # Do NOT modify code below           #
 ######################################
 
+PARENT="$(dirname $0)"
+[[ -z ${BRANCH} ]] && { [[ -f "${PARENT}"/.env_branch ]] && BRANCH=$(cat "${PARENT}"/.env_branch) || BRANCH=master; }
+URL_RAW="https://raw.githubusercontent.com/cardano-community/guild-operators/${BRANCH}"
+URL="${URL_RAW}/scripts/cnode-helper-scripts"
+URL_DOCS="${URL_RAW}/docs/Scripts"
+
 versionCheck() { printf '%s\n%s' "${1//v/}" "${2//v/}" | sort -C -V; } #$1=minimal_needed_version, $2=current_node_version
 
 OFFLINE_MODE='N'
@@ -175,7 +181,7 @@ else
 fi
 
 if [[ -z ${EKG_PORT} ]]; then
-  if ! EKG_PORT=$(jq -er '.hasEKG' "${CONFIG}" 2>/dev/null); then
+  if ! EKG_PORT=$(jq -er '.hasEKG | if .|type=="array" then .[1] else . end' "${CONFIG}" 2>/dev/null); then
     if [[ ${OFFLINE_MODE} = "N" ]]; then
       echo "Could not get 'hasEKG' port in ${CONFIG}"
       return 1
@@ -250,6 +256,8 @@ fi
 BLOCKLOG_DB="${BLOCKLOG_DIR}/blocklog.db"
 [[ -z ${BLOCKLOG_TZ} ]] && BLOCKLOG_TZ="UTC"
 [[ -z ${CNODE_PORT} ]] && CNODE_PORT=6000
+[[ -z "${IP_VERSION}" ]] && IP_VERSION=4
+IP_VERSION=$(tr '[:upper:]' '[:lower:]' <<< "${IP_VERSION}")
 
 CNODE_PID=$(pgrep -fn "[c]ardano-node.*.--port ${CNODE_PORT}")
 
@@ -267,6 +275,7 @@ if [[ -n "${CNODE_PID}" ]]; then
   fi
 fi
 
+[[ -z ${UPDATE_CHECK} ]] && UPDATE_CHECK="Y"
 [[ -z ${TOPOLOGY} ]] && TOPOLOGY="${CNODE_HOME}/files/topology.json"
 [[ -n ${CNODE_TOPOLOGY} ]] && TOPOLOGY="${CNODE_TOPOLOGY}" # compatibility with older topologyUpdater
 [[ -z ${LOG_DIR} ]] && LOG_DIR="${CNODE_HOME}/logs"
@@ -311,8 +320,8 @@ if ! mkdir -p "${TMP_DIR}" 2>/dev/null; then echo "ERROR: Failed to create direc
 [[ -z ${ASSET_POLICY_ID_FILENAME} ]] && ASSET_POLICY_ID_FILENAME="policy.id"
 
 node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "1.25.1" "${node_version}"; then
-  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.25.1 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
+if ! versionCheck "1.26.0" "${node_version}"; then
+  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.26.0 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
   return 1
 fi
 
@@ -355,22 +364,283 @@ STANDOUT='\e[7m'
 BOLD='\e[1m'
 NC='\e[0m'
 
-
+# Description : Query user for yes or no answer
 getAnswer() {
-  printf "$* (yes/no): " >&2; read -r answer
+  getAnswerAny answer "$* (yes/no)"
   while : ; do
     case $answer in
       [Yy]*) return 0 ;;
       [Nn]*) return 1 ;;
-      *) printf "%s" "Please enter 'yes' or 'no' to continue: " >&2; read -r answer
+      *) getAnswerAny answer "Please enter 'yes' or 'no' to continue"
     esac
   done
 }
 
+# Description : Query user for any question
+#             : $1 = the name of the variable to save users response into
+#             : $2 = what to ask user to input
+getAnswerAny() {
+  var_name=$1
+  shift
+  printf "%b: ${FG_GREEN}" "$*"
+  read -r ${var_name} </dev/tty
+  printf "${NC}"
+}
+
+# Description : Query user for any question
+#             : $1 = name of script to update
+#             : $2 = [Y|N] ignore question and auto update
+# return code : 0 = no update
+#             : 1 = update applied
+#             : 2 = update failed
+checkUpdate() {
+  [[ "${UPDATE_CHECK}" != "Y" ]] && return 0
+  if curl -s -f -m 10 -o "${PARENT}/${1}".tmp "${URL}/${1}" 2>/dev/null; then
+    # get vname from env file
+    if [[ $(grep "_HOME=" "${PARENT}"/env) =~ ^#?([^[:space:]]+)_HOME ]]; then
+      vname=$(tr '[:upper:]' '[:lower:]' <<< ${BASH_REMATCH[1]})
+      # replace default CNODE with custom name if needed
+      [[ ${vname} != cnode ]] && sed -e "s@/opt/cardano/[c]node@/opt/cardano/${vname}@g" -e "s@[C]NODE_HOME@${BASH_REMATCH[1]}_HOME@g" -i "${PARENT}/${1}".tmp
+    else
+      printf "${FG_RED}ERROR${NC}: '${1}' update failed! Please use prereqs.sh to force an update or manually download the file from GitHub"
+      return 2
+    fi
+    TEMPL_CMD=$(awk '/^# Do NOT modify/,0' "${PARENT}/${1}")
+    TEMPL2_CMD=$(awk '/^# Do NOT modify/,0' "${PARENT}/${1}".tmp)
+    if [[ "$(echo ${TEMPL_CMD} | sha256sum)" != "$(echo ${TEMPL2_CMD} | sha256sum)" ]]; then
+      if [[ $2 = Y ]] || { [[ -t 1 ]] && getAnswer "\nThe static content from ${FG_YELLOW}${1}${NC} does not match with guild-operators repository, do you want to download the updated file?"; }; then
+        cp "${PARENT}/${1}" "${PARENT}/${1}_bkp$(date +%s)"
+        STATIC_CMD=$(awk '/#!/{x=1}/^# Do NOT modify/{exit} x' "${PARENT}/${1}")
+        printf '%s\n%s\n' "$STATIC_CMD" "$TEMPL2_CMD" > "${PARENT}/${1}".tmp
+        mv "${PARENT}/${1}".tmp "${PARENT}/${1}"
+        echo -e "\n${FG_YELLOW}${1}${NC} update successfully applied!"
+        [[ -t 1 ]] && waitToProceed && clear
+        return 1
+      fi
+    fi
+  fi
+  rm -f "${PARENT}/${1}".tmp
+  return 0
+}
+
+# Description : Check if command is available
+#             : $1 = executable to validate
+cmdAvailable() {
+  if ! command -v "$1" &>/dev/null; then
+    printf "${FG_RED}ERROR${NC}: need '$1' (command not found)\nplease install with your packet manager of choice(apt/yum etc..) and relaunch CNTools\nhttps://command-not-found.com/$1" 1>&2
+    return 1
+  fi
+  return 0
+}
+
+# Description : wait for user keypress to continue
+# Parameters  : message  >  [optional]: override default 'press any key to return to home menu' message
 waitToProceed() {
-  printf "\npress any key to proceed..."
-  read -r -n 1 -s wait
-  clear
+  IFS=';' read -sdR -p $'\E[6n' ROW COL
+  echo
+  createDistanceToBottom $(( $# + 1 ))
+  ESC=$(printf "\033")
+  echo
+  if [[ $# -eq 0 || -z $1 ]]; then
+    echo "press any key to proceed .."
+  else
+    printf '%b\n' "$@"
+  fi
+  read -rsn1 key # get 1 character
+  if [[ $key == "$ESC" ]]; then
+    read -rsn2 key # read 2 more chars
+  fi
+  tput cup ${ROW#*[} ${COL}
+  tput ed
+}
+
+# Description : Generate asset id according to CIP-14 standard
+#               https://github.com/cardano-foundation/CIPs/pull/64
+#             : $1 = hex-encoded policy ID
+#             : $2 = ASCII formatted asset name
+getAssetIDBech32() {
+  { ! cmdAvailable "bech32" || ! cmdAvailable "b2sum"; } && return 1
+  printf "$(echo -n $1 | sed 's/../\\x&/g')%s" "$2" | b2sum -l 160 -b | cut -d' ' -f 1 | bech32 asset
+}
+
+# Description : Convert a normal 1 byte ASCII string to hex (alnum chars)
+#             : $1 = ASCII string to convert
+asciiToHex() {
+  local ascwrd=$1
+  [[ -z ${ascwrd} ]] && return
+  for ((i=0;i<${#ascwrd};i++)); do
+    printf %02x \'${ascwrd:$i:1}
+  done
+}
+
+# Description : Helper function to validate that input is a number
+#             : $1 = number
+isNumber() {
+  [[ -z $1 ]] && return 1
+  [[ $1 =~ ^[0-9]+$ ]] && return 0 || return 1
+}
+
+# Description : Validate decimal number
+#             : $1 = decimal number to validate
+validateDecimalNbr() {
+  re_decimal_nbr='^[0-9]+([.][0-9]+)?$'
+  [[ $1 =~ ${re_decimal_nbr} ]] && return 0 || return 1
+}
+
+# Description : Pretty print Lovelace value
+#             : $1 = Amount in Lovelace
+formatLovelace() {
+  if isNumber $1; then
+    [[ $1 -eq 0 ]] && echo 0 && return
+    [[ $1 -le 999999 ]] && printf '0.%06d' "$1" && return
+    printf '%s.%s' "$(sed ':a;s/\B[0-9]\{3\}\>/,&/;ta' <<< ${1::-6})" "${1: -6}"
+  else
+    printf "${FG_RED}ERROR${NC}: must be a valid integer number" 1>&2
+    return 1
+  fi
+}
+
+# Description : Pretty print Ada/Token value
+#             : $1 = Amount as Integer
+formatAsset() {
+  if isNumber $1; then
+    sed ':a;s/\B[0-9]\{3\}\>/,&/;ta' <<< $1
+  else
+    printf "${FG_RED}ERROR${NC}: must be a valid integer number" 1>&2
+    return 1
+  fi
+}
+
+# Description : Convert number in Ada to Lovelace
+#             : $1 = Amount in Ada, decimal number accepted (using dot)
+AdaToLovelace() {
+  if validateDecimalNbr $1; then
+    echo "$1 * 1000000 / 1" | bc # /1 is to remove decimals from bc command
+  else
+    printf "${FG_RED}ERROR${NC}: must be a valid integer or decimal number" 1>&2
+    return 1
+  fi
+}
+
+# Description : Convert number as percent to fraction
+#             : $1 = number to be converted in range 0-100
+pctToFraction() {
+  if validateDecimalNbr $1; then
+    if [[ $(bc <<< "$1 >= 0" ) -eq 0 || $(bc <<< "$1 <= 100" ) -eq 0 ]]; then
+      printf "${FG_RED}ERROR${NC}: must be a number between 0-100" 1>&2
+      return 1
+    else
+      echo "x=$1 / 100; if(x<1) print 0; x" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//'
+    fi
+  else
+    printf "${FG_RED}ERROR${NC}: must be a valid integer or decimal number" 1>&2
+    return 1
+  fi
+}
+
+# Description : Convert fraction number to precent
+#             : $1 = number to be converted
+fractionToPCT() {
+  if validateDecimalNbr $1; then
+    if (( $(bc <<<"$1 > 0") )); then
+      echo "x=$1 * 100; if(x<1) print 0; x" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//'
+    else
+      echo 0
+    fi
+  else
+    printf "${FG_RED}ERROR${NC}: must be a valid decimal number" 1>&2
+    return 1
+  fi
+}
+
+# Description : Helper function to validate IPv4 address
+#             : $1 = IP
+isValidIPv4() {
+  local ip=$1
+  [[ -z ${ip} ]] && return 1
+  if [[ ${ip} =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ || ${ip} =~ ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$ ]]; then
+    return 0
+  fi
+  return 1
+}
+
+# Description : Get password from user on STDIN
+#             : populates ${password} variable, make sure to unset variable when done
+#             : $1 = Minimum password length
+#             : $2 = The string 'confirm' to force user to provide password twice for confirmation (optional)
+getPassword() {
+  while true; do
+    readPassword "Enter password (length >= 8)"
+    password=${read_password} && unset read_password
+    if [ ${#password} -lt $1 ]; then
+      echo
+      echo -e "${FG_RED}ERROR${NC}: password length too short, please use a minimum of $1 characters."
+      echo
+      echo "Press q to abort or any other key to retry"
+      read -rsn 1 abort
+      [[ ${abort} = "q" ]] && unset password && return 1
+      echo
+      continue
+    fi
+    if [[ $2 = "confirm" ]]; then
+      echo && readPassword "Confirm password"
+      check_password=${read_password} && unset read_password
+      if [[ "${password}" != "${check_password}" ]]; then
+        echo
+        echo -e "${FG_RED}ERROR${NC}: password missmatch!"
+        echo
+        echo "Press q to abort or any other key to retry"
+        read -rsn 1 abort
+        [[ ${abort} = "q" ]] && unset password && unset check_password && return 1
+        echo
+      else
+        echo && unset check_password && return 0
+      fi
+    else
+      echo && return 0
+    fi
+  done
+}
+readPassword() {
+  read_password=""
+  prompt="$1: "
+  while IFS= read -p "${prompt}" -r -s -n 1 char; do
+    if [[ ${char} == $'\0' ]]; then break; fi
+    if [[ ${char} == $'\b' ]]; then
+      [[ ${#read_password} -gt 0 ]] && printf "\033[1D\033[0K" && read_password=${read_password%?}
+      prompt=''
+    else
+      prompt='*'
+      read_password+="${char}"
+    fi
+  done
+}
+
+# Description : Helper function to validate IPv6 address, works for normal IPv6 addresses, not dual incl IPv4
+#             : $1 = IP
+isValidIPv6() {
+  local ip=$1
+  [[ -z ${ip} ]] && return 1
+  ipv6_regex="^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$"
+  [[ ${ip} =~ ${ipv6_regex} ]] && return 0
+  return 1
+}
+
+# Description : Helper function to validate if IP address is in a private range
+#             : $1 = IP
+isPrivateIP() {
+  local ip=$1
+  [[ -z ${ip} ]] && return 1
+  private_ip_regex="^(127\.|0?10\.|172\.0?1[6-9]\.|172\.0?2[0-9]\.|172\.0?3[0-2]\.|192\.168\.|169\.254\.|::1|[fF][cCdD][0-9a-fA-F]{2}:|[fF][eE][89aAbB][0-9a-fA-F]:)"
+  [[ ${ip} =~ ${private_ip_regex} ]] && return 0
+  return 1
+}
+
+# Description : Print blank rows and reset cursor position
+#             : $1 = number of rows
+createDistanceToBottom() {
+  printf "%0.s\n" $(seq $1)
+  printf "\033[$1A"
 }
 
 # Description : Query cardano-node for current metrics
@@ -537,9 +807,8 @@ if [[ ${OFFLINE_MODE} = "N" && ! -S ${CARDANO_NODE_SOCKET_PATH} ]]; then
   return 2
 fi
 
-if ! getEraIdentifier; then echo "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}" && return 2; fi
+if [[ ${OFFLINE_MODE} = "N" ]] && ! PROT_PARAMS="$(${CCLI} query protocol-parameters ${NETWORK_IDENTIFIER} 2>&1)"; then echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}" && return 2; fi
 
-PROT_PARAMS="$(${CCLI} query protocol-parameters ${ERA_IDENTIFIER} ${NETWORK_IDENTIFIER} 2>&1)"
-if [[ -n "${PROT_PARAMS}" ]] && ! DECENTRALISATION=$(jq -er .decentralisationParam <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
+if ! DECENTRALISATION=$(jq -er .decentralization <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
 
 return 0
